### ISSUE TITLE
Max Value subtracts one when sliding min handle

### ISSUE THREAD

**Issue by mjarrison** [maxshuty/accessible-web-components#5] opened 2022-08-23 19:22 UTC
On most of the examples on the demo, you can recreate this problem.

https://maxshuty.github.io/accessible-web-components/

The first example starts with a range of 1-1000.
If the min handle is dragged slightly up, the resulting range has a max value of 999 instead of the expected 1000.

**Comment by maxshuty** [comment] 2022-12-29 21:16
Thanks for reporting @mjarrison. I was able to reproduce the issue and will hopefully have a resolution in the next release. It appears to only happen when there are large ranges which is interesting.

**Comment by maxshuty** [comment] 2023-01-09 21:27
I've been digging into this one, it was quite tricky to figure out what the issue is. 

Long story short... it's complicated.

The plugin currently takes the average of the `minimum` and `maximum` values. If, for example, you have a min of `1` and a max of `1000` then it ends up with an average of `500.5` which is set as the minimum for the right side of the slider (the higher number). With a `step="1"` it goes up by 1 for each increment on the slider which ultimately reaches the maximum of `999.5`. Then when you slide it the slider re-draws and you end up with it going down to `999` initially because of some `Math.floor` logic.

I am currently working on the fix for this. I will post an update here once fixed.

**Comment by maxshuty** [comment] 2023-01-11 12:42
This has been fixed in `v1.0.7`. Thanks for reporting!

**Closed as completed** 2023-01-11 12:41 UTC
